# Generated by Django 2.2.5 on 2019-09-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizzeras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
