# Generated by Django 2.2.5 on 2019-09-25 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_pizzeras'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('pizzera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_logs.Pizzeras')),
            ],
            options={
                'verbose_name_plural': 'Topping',
            },
        ),
    ]
